name: bochki_schedule_app
description: Application package for the Bochki Schedule desktop app.
publish_to: none
version: 0.6.0

environment:
  sdk: ^3.5.0

dependencies:
  archive: ^4.0.7
  bochki_schedule_domain:
    path: ../bochki_schedule_domain
  bochki_schedule_infra:
    path: ../bochki_schedule_infra
  flutter:
    sdk: flutter
  path: ^1.9.0
  window_manager: ^0.4.3

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
