name: bochki_schedule_infra
description: Infrastructure package for Bochki Schedule.
publish_to: none
version: 0.7.0

environment:
  sdk: ^3.5.0

dependencies:
  bochki_schedule_domain:
    path: ../bochki_schedule_domain
  path: ^1.9.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
